Selenium - RDI happy path
unicef/hct-mis pull request #3750
Opened 2024-03-29 08:08 UTC by szymon-kellton

2024-04-04 07:56 UTC, pavlo-mk submitted a review, later dismissed

2024-04-04 19:39 UTC, KonradMarzec1991 requested changes

2024-04-04 19:39 UTC, KonradMarzec1991 commented on backend/selenium_tests/page_object/programme_population/households.py
> +    mainContent = 'div[data-cy="main-content"]'
Many of these attributes and methods can be separated into more general class. Then that class can be used for inheritance

2024-04-05 07:37 UTC, pavlo-mk approved these changes

2024-04-05 11:14 UTC, KonradMarzec1991 approved these changes

2024-04-08 06:07 UTC, merged