[196847] No validate end date for existing programmes
unicef/hct-mis pull request #3847
Opened 2024-05-09 12:32 UTC by patryk-dabrowski

AB#196847

2024-05-09 14:02 UTC, mmaciekk approved these changes

2024-05-10 08:20 UTC, pkujawa requested changes
According to the requirements (specified more in the comments) - the validation should be omitted only if editing FINISHED program

2024-05-10 08:45 UTC, patryk-dabrowski commented
> According to the requirements (specified more in the comments) - the validation should be omitted only if editing FINISHED program

@pkujawa What do you mean by FINISHED program? we cannot edit programs with FINISHED status at all

2024-05-10 08:51 UTC, pkujawa approved these changes

2024-05-13 07:33 UTC, merged