Test rdi kobo
unicef/hct-mis pull request #4066
Opened 2024-07-19 10:38 UTC by patryk-dabrowski

2024-07-23 08:13 UTC, pavlo-mk approved these changes

2024-07-23 12:12 UTC, szymon-kellton requested changes

2024-07-23 12:12 UTC, szymon-kellton commented on backend/selenium_tests/registration_data_import/test_registration_data_import.py
> +        # pageRegistrationDataImport.checkLoadingProgressCircle()
Please delete unnecessary comments?

2024-07-23 12:12 UTC, szymon-kellton commented on backend/selenium_tests/registration_data_import/test_registration_data_import.py
> +        # pageRegistrationDataImport.checkLoadingProgressCircle()
Please delete unnecessary comments?

2024-07-23 12:12 UTC, szymon-kellton commented on backend/selenium_tests/registration_data_import/test_registration_data_import.py
> +        Area.objects.create(name="Andara", p_code="NG008003001", area_type=area_type_3, parent=area_2)
From 
business_area = BusinessArea.objects.get(name="Afghanistan") 
to
Area.objects.create(name="Andara", p_code="NG008003001", area_type=area_type_3, parent=area_2)

From my perspective that should be in separate pytest fixture/fixtures. Consider for test clearance.

2024-07-23 12:12 UTC, szymon-kellton commented on backend/selenium_tests/registration_data_import/test_registration_data_import.py
> +        # pageRegistrationDataImport.checkLoadingProgressCircle()
Please delete unnecessary comments?

2024-07-23 12:12 UTC, szymon-kellton commented on backend/selenium_tests/registration_data_import/test_registration_data_import.py
> +        # pageRegistrationDataImport.checkLoadingProgressCircle()
Please delete unnecessary comments?

2024-07-25 12:21 UTC, szymon-kellton approved these changes

2024-07-25 15:02 UTC, merged